FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /app


# copy csproj and restore as distinct layers
COPY *.sln .
COPY WebApplication2/*.csproj ./WebApplication2/
RUN dotnet restore

# copy everything else and build app
COPY WebApplication2/. ./WebApplication2/
WORKDIR /app/WebApplication2
RUN dotnet publish -c Release -o output



FROM microsoft/dotnet:2.1-aspnetcore-runtime AS runtime
WORKDIR /app
copy --from=build /app/WebApplication2/output .
ENTRYPOINT ["dotnet", "WebApplication2.dll"]